name: Unit test
on:
  push:
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Install gotest
      run: |
        go install github.com/rakyll/gotest@latest
        go get -u github.com/axw/gocov/gocov
        go mod tidy

    - name: Tests
      run: make test/action/unit
